# Generated by Django 5.2.4 on 2025-07-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntelligentSearchSetup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("url", models.CharField(max_length=255, unique=True)),
                ("shared_secret", models.CharField(max_length=128)),
                ("index_setup", models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
